package main

import (
	"fmt"
	"jianshu-go"
)

func main() {

	fmt.Println("**** Test one ****")
	user := jianshu.NewUser("https://www.jianshu.com/u/b7d7dfdc14fb", "", "")
	fmt.Println(user.GetUserID())
	fmt.Println(user.GetUserGender())
	fmt.Println(user.GetUserLink())
	fmt.Println(user.GetFollowNumber())
	fmt.Println(user.GetFollowerNumber())
	fmt.Println(user.GetPassageNumber())
	fmt.Println(user.GetWriteNumber())
	fmt.Println(user.GetLikeNumber())
	fmt.Println(user.GetHomepagePassage())
	fmt.Println(user.GetPersonalDetail())
	fmt.Println(user.GetTwitterInfo())
	fmt.Sprint(user.GetLikedNotes())
	fmt.Println(user.GetSubscription())
	//fmt.Println(jianshu.GetUuidFromLink(user))

	fmt.Println("**** Test two ****")
	user2 := jianshu.NewUser("https://www.jianshu.com/u/3c1c79ba19f3", "", "")
	fmt.Println(user2.GetUserID())
	fmt.Println(user2.GetUserGender())
	fmt.Println(user2.GetUserLink())
	fmt.Println(user2.GetFollowNumber())
	fmt.Println(user2.GetFollowerNumber())
	fmt.Println(user2.GetPassageNumber())
	fmt.Println(user2.GetWriteNumber())
	fmt.Println(user2.GetLikeNumber())
	fmt.Println(user2.GetHomepagePassage())
	fmt.Println(user2.GetPersonalDetail())
	fmt.Println(user2.GetTwitterInfo())
	fmt.Sprint(user2.GetLikedNotes())
	fmt.Println(user2.GetSubscription())
	fmt.Println("**** Test three ****")
	user3 := jianshu.NewUser("https://www.jianshu.com/users/fefb7dffd893/timeline", "", "")
	fmt.Println(user3.GetUserID())
	fmt.Println(user3.GetUserGender())
	fmt.Println(user3.GetUserLink())
	fmt.Println(user3.GetFollowNumber())
	fmt.Println(user3.GetFollowerNumber())
	fmt.Println(user3.GetPassageNumber())
	fmt.Println(user3.GetWriteNumber())
	fmt.Println(user3.GetLikeNumber())
	fmt.Println(user3.GetHomepagePassage())
	fmt.Println(user3.GetPersonalDetail())
	fmt.Println(user3.GetTwitterInfo())
	fmt.Sprint(user3.GetLikedNotes())
	fmt.Println(user3.GetSubscription())
	fmt.Println(jianshu.GetUuidFromLink(user3))
	fmt.Println("**** Test Four ****")
	user4 := jianshu.NewUser("https://www.jianshu.com/u/1441f4ae075d", "", "")
	fmt.Println(user4.GetUserID())
	fmt.Println(user4.GetUserGender())
	fmt.Println(user4.GetUserLink())
	fmt.Println(user4.GetFollowNumber())
	fmt.Println(user4.GetFollowerNumber())
	fmt.Println(user4.GetPassageNumber())
	fmt.Println(user4.GetWriteNumber())
	fmt.Println(user4.GetLikeNumber())
	fmt.Println(user4.GetHomepagePassage())
	fmt.Println(user4.GetPersonalDetail())
	fmt.Println(user4.GetTwitterInfo())
	fmt.Sprint(user4.GetLikedNotes())
	fmt.Println(user4.GetSubscription())
}
